spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: rgukt123

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka