spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: rgukt123

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8081

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka